# This is a basic workflow to help you get started with Actions

name: more_jobs


on:
  schedule:
    - cron: '32 13 * * 1,2,3'

  workflow_dispatch:

env:
  DAY_OF_WEEK: Monday
  First_Name: Hampus

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Print current day
        run: echo "Today is $DAY_OF_WEEK
