name: Weather With You

on:
  push:
    branches: [ "TPS6" ]
  workflow_dispatch:
    inputs:
      logging_errors:
        description: "Skapa logg om tester misslyckas"
        required: true
        default: "true"
        type: choice
        options: ["true", "false"]

env:
  PYTHON_VERSION: "3.11"
  IMAGE_NAME: plyschbjorn/weather-with-you
  DOCKERFILE_PATH: ./dockerfile
  DOCKER_TAG_LATEST: latest

jobs:

  environment_check:
    name: Environment check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pytest

  tests:
    name: Run tests
    runs-on: ubuntu-latest
    needs: environment_check

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pytest

      - name: Run pytest
        run: |
          set -o pipefail
          mkdir -p junit
          pytest tests/test_get_api.py tests/test_dashboard.py | tee junit/pytest-output.txt || echo "TESTS_FAILED=true" >> $GITHUB_ENV

      - name: Upload test log (endast vid workflow_dispatch + param true + tester faller)
        if: ${{ env.TESTS_FAILED == 'true' && github.event_name == 'workflow_dispatch' && github.event.inputs.logging_errors == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: pytest-log
          path: junit/pytest-output.txt

      - name: Fail job if tests failed
        if: ${{ env.TESTS_FAILED == 'true' }}
        run: |
          echo "Test har misslyckats"
          exit 1

  build_and_push:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    needs: tests
    if: needs.tests.result == 'success'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG_LATEST }}